name: pull_to_refresh_new
description: A refresh indicator widget that supports android, ios, and web.
version: 2.0.3
homepage: https://github.com/ssh199956/pull_to_refresh_new

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true